# Generated by Django 2.2.16 on 2022-06-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220608_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('pk',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
